import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "currency converter",
  description: "Generated by 0613",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
